# Generated by Django 2.2.7 on 2019-11-09 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindartapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='buffer',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='artist',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='firstname',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='lastname',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
