# Generated by Django 2.2.7 on 2019-11-09 22:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tindartapp', '0002_auto_20191109_2222'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='art',
            name='buffer',
        ),
        migrations.AddField(
            model_name='art',
            name='artist',
            field=models.ForeignKey(max_length=200, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='artwork', to='tindartapp.Artist'),
        ),
    ]
