# Generated by Django 2.2.7 on 2019-11-10 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindartapp', '0003_auto_20191110_1616'),
    ]

    operations = [
        migrations.AlterField(
            model_name='art',
            name='user',
            field=models.CharField(max_length=200),
        ),
    ]
