# Generated by Django 2.2.7 on 2019-11-09 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindartapp', '0003_auto_20191109_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='artwork',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
