# Generated by Django 2.2.7 on 2019-11-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tindartapp', '0004_auto_20191110_1622'),
    ]

    operations = [
        migrations.AddField(
            model_name='art',
            name='dislikes',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
